<?php

/*
    USER HELPER

    This is a helper file, generated by Leonard.
    This is NOT laravel default. Whenever you need to statically define
    something, ALWAYS do it via helpers, so that those things
    can be changed in the future / overloaded without a hassle.
*/

namespace App\Helpers;

use Spatie\Permission\Models\Role;


class UserHelper {
    // public static function userTypes() : object {

    //     // $userTypes = array(
    //     //     array(
    //     //         'user' => 'Basic user'
    //     //     )
    //     // )

    //     return (object) $userTypes;
    // }

    public static function roles() : object {
        $all_roles_in_the_database = Role::all()->pluck('name');
        return (object) $all_roles_in_the_database;
    }
}
